@startuml Codecouleur
left to right direction
skinparam actorStyle awesome
skinparam backgroundcolor Grey/Black
skinparam classBackgroundColor Wheat|CornflowerBlue
package Administration #White{
    actor Admin as ADMIN #Gold
    actor SuperAdmin as SUPADMIN #WhiteSmoke
}


Rectangle Quidideance #DarkCyan {

    ("Surfer sur le site") as SURF #White
    
package Administrer #DarkSeaGreen/SeaGreen {
    ("Créer un admin") as ADMNEW #White
    ("Modifier un admin") as ADMEDIT #White
    ("Supprimer un admin") as ADMDELETE #White
    ("Voir un admin") as ADMSHOW #White
}    
package Interroger #RoyalBlue/LightBlue {

    ("Créer une question") as INTNEW #White
    ("Modifier une question") as INTEDIT #White
    ("Supprimer une question") as INTDELETE #White
    ("Voir une question") as INTSHOW #White
}
package Questionner #Orange/OrangeRed {

    ("Créer un questionnaire") as QUENEW #White
    ("Modifier un questionnaire") as QUEEDIT #White
    ("Supprimer un questionnaire") as QUEDELETE #White
    ("Voir un questionnaire") as QUESHOW #White
}

package Répondre #Purple/MediumPurple {

    ("Créer une réponse") as REPNEW #White
    ("Modifier une réponse") as REPEDIT #White
    ("Supprimer une réponse") as REPDELETE #White
    ("Voir une réponse") as REPSHOW #White
}
package Gérer #LightCoral/DarkBlue {

    ("Gérer") as GER #WhiteSmoke
    ("Modifier son compte") as GEREDIT #White
    ("Voir ses informations") as GERSHOW #White
}
package Authentifier #Grey/DarkGrey {
    ("Se connecter") as CON #White
    ("Se déconnecter") as DEC #White
}


    SUPADMIN--|> ADMIN : Généralisation Super admin à admin



    ADMIN--up->CON #Gold
    ADMIN--->DEC #Gold
    ADMIN-->SURF #Gold



    ADMIN--->QUENEW #Gold : un admin ne pourra que créer son questionnaire
    QUENEW<..-QUEEDIT #Gold : un admin ne pourra que modifier son questionnaire Include
    QUENEW<..-QUEDELETE #Gold : un admin ne pourra que supprimer son questionnaire Include
    QUENEW<..-QUESHOW #Gold : Include 

    ADMIN--->INTNEW #Gold
    INTNEW<..-INTEDIT #Gold : Include
    INTNEW<..-INTDELETE #Gold : Include
    INTNEW<..-INTSHOW #Gold : Include

    ADMIN--->REPNEW #Gold
    REPNEW<..-REPEDIT #Gold : Include
    REPNEW<..-REPDELETE #Gold : Include
    REPNEW<..-REPSHOW #Gold : Include

    ADMIN--->GER #Gold
    GER-..>GEREDIT #Gold : Extend
    GER-..>GERSHOW #Gold : Extend

    SUPADMIN----->ADMNEW #WhiteSmoke
    ADMNEW<..-ADMEDIT #WhiteSmoke : Include
    ADMNEW<..-ADMDELETE #WhiteSmoke : Include
    ADMNEW<..-ADMSHOW #WhiteSmoke : Include

    CON<.-DEC #White : Include
    SUPADMIN-.>CON #White : Include
    GER-.>CON #White : Include
    QUENEW<..-INTNEW #White : Include
    INTNEW<..-REPNEW #White : Include
    
    
    
    
    



      
    
  
}

@enduml
