@startuml Codecouleur
left to right direction
skinparam actorStyle awesome
skinparam BackgroundColor #DarkCyan
package Personnesurlesite #Grey {
actor Visiteur as VIS #Blue
}

[Le service API] as API #pink


Rectangle Application #DarkGrey {

    ("Surfer sur le site") as SURF
    ("Choisir") as CHO
    ("Choisir les couleurs") as CHOCOULEUR  
    ("Choisir la taille d'écriture") as CHOTAILLE
    ("Voir le résultat") as VOI
    ("Couleur") as COU
    ("Ajouter couleur") as COUNEW
    ("Modifier couleur") as COUEDIT
    ("Supprimer couleur") as COUDELETE    

    VIS-->SURF #Blue
    VIS-->CHO #Blue
    CHOCOULEUR-left-->CHO : extend
    CHOTAILLE-left->CHO : extend
    VOI-up-CHOCOULEUR : include
    VOI-up-CHOTAILLE : include
    COU---->COUNEW
    COU---->COUEDIT
    COU---->COUDELETE
    COU-up->CHOCOULEUR
   
    API-left->COU
}

@enduml
