@startuml administrer
autonumber 
actor Superadmin #Black
Superadmin -> Administrer : Afficher interface administrer
activate Administrer #SkyBlue
Administrer --> Superadmin : Interface affichée
deactivate Administrer
alt #GreenYellow Cas valdide 
Administrer --> Superadmin : Accès à la page d'administration
else #IndianRed Cas problème
Administrer --> Superadmin : Erreur server redirection sur la page d'accueil
end
Visiteur -> Connexion : Afficher interface connexion
activate Connexion #SkyBlue
Connexion --> Visiteur : Interface affichée
deactivate Connexion
alt #GreenYellow Cas valdide 
Nousconnaitre --> Visiteur : Accès à la page connexion
else #IndianRed Cas problème
Nousconnaitre --> Visiteur : Erreur server redirection sur la page d'accueil
end
@enduml