@startuml
actor Admin 
Admin -> MDP.oublié --+ : Afficher interface MDP oublié
MDP.oublié --> Admin --+ : Interface affichée
alt #GreenYellow Cas valdide 
MDP.oublié --> Admin --+: Envoie d'un nouveau mot de passe par email
else #IndianRed Cas problème
MDP.oublié --> Admin --+: Erreur server redirection sur la page d'accueil
MDP.oublié --> Admin --+: Erreur d'adresse email retour mdp oublié
end
MDP.oublié -> MONQ --+ : BLBALABLA
MDP.oublié -> MONQ --+ : STOP
MONQ -> MDP.oublié  --+ : Allo
MDP.oublié -> MONQ  --+ : Bravo
MONQ -> MDP.oublié --+ : HAHAHAHA
Dodo -> Valdo +---------------------+: Debut
activate Dodo
Valdo -> Dodo +---------------------+ : Fin
activate Valdo


@enduml