@startuml voirquestionnaire
autonumber 
actor Administrateur #Black
Administrateur -> Questionnaire : Afficher interface questionnaire
activate Questionnaire #SkyBlue
Questionnaire --> Administrateur : Interface affichée
deactivate Questionnaire
alt #GreenYellow Cas valide 
Utilisateur <-- Administrateur : Accès à la page d'administration questionnaire
else #IndianRed Cas problème
Utilisateur --> Administrateur : Erreur server redirection sur la page d'accueil
end
Utilisateur -> Voir : Redirection sur la page
Voir -> Validation : Afficher interface voir un questionnaire
activate Validation #SkyBlue
Validation --> Voir : Interface affichée
deactivate Validation
alt #GreenYellow Cas valdide 
Voir --> Validation : Redirection à la page voir du questionnaire
else #IndianRed Cas problème
Voir <-- Validation : Erreur server redirection sur la page d'accueil
end
@enduml