@startuml creerquestionnaire
autonumber 
actor Administrateur #Black
Administrateur -> Questionnaire : Afficher interface questionnaire
activate Questionnaire #SkyBlue
Questionnaire --> Administrateur : Interface affichée
deactivate Questionnaire
alt #GreenYellow Cas valide 
Questionnaire <-- Administrateur : Accès à la page d'administration d'un questionnaire
else #IndianRed Cas problème
Questionnaire --> Administrateur : Erreur server redirection sur la page d'accueil
end
Questionnaire -> Créer : Redirection sur la page
Créer -> Validation : Afficher interface créer un questionnaire
activate Validation #SkyBlue
Validation --> Créer : Interface affichée
loop #LightGrey Séquence enregistrement
Administrateur ->> Validation : Ajout de question
Administrateur ->> Validation : Ajout de réponse
Administrateur ->> Validation : Sélection d'une date de début pour valider le questionnaire
Administrateur ->> Validation : Sélection d'une date de fin pour valider le questionnaire
Administrateur -> Validation : Cliquer sur Enregistrer
Validation -[#Black]> Validation : Contrôle de saisie
Validation --> Administrateur : Afficher exception
end
deactivate Validation
alt #GreenYellow Cas valide 
Créer --> Validation : Validation de l'enregistrement. Accès à la page d'administration questionnaire
Validation --> Questionnaire : Affichage du message "Ajout créé avec succès"
else #IndianRed Cas problème
Créer <-- Validation : Erreur server redirection sur la page d'accueil
Créer <-- Validation : Erreur lors de la saisie des champs. Affichage d'un message "Veuillez remplir les champs signalés !"
Créer <-- Validation : Erreur lors de la sélection d'une date. Affichage d'un message "Veuillez sélectionner d'une date !" 
Créer <-- Validation : Erreur lors de la validation de l'enregistrement. Affichage d'un message 
end
@enduml