@startuml supprimerquestionnaire
autonumber 
actor Administrateur #Black
Administrateur -> Questionnaire : Afficher interface questionnaire
activate Questionnaire #SkyBlue
Questionnaire --> Administrateur : Interface affichée
deactivate Questionnaire
alt #GreenYellow Cas valide 
Questionnaire <-- Administrateur : Accès à la page d'administration questionnaire
else #IndianRed Cas problème
Questionnaire --> Administrateur : Erreur server redirection sur la page d'accueil
end
Questionnaire -> Supprimer : Redirection sur la page
Supprimer -> Validation : Afficher interface supprimer un questionnaire
activate Validation #SkyBlue
Validation --> Supprimer : Interface affichée
deactivate Validation
alt #GreenYellow Cas valdide 
Supprimer --> Validation : Validation de la suppression. Accès à la page d'administration questionnaire
Validation --> Questionnaire : Affichage du message "Suppression effectuéé avec succès"
else #IndianRed Cas problème
Supprimer <-- Validation : Erreur server redirection sur la page d'accueil
end
@enduml